spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-management
          uri: lb://inventory-management
          predicates:
            - Path=/api/inventory/**
        - id: room-management
          uri: lb://room-management
          predicates:
            - Path=/api/rooms/**
        - id: user-system
          uri: lb://user-system
          predicates:
            - Path=/api/users/**
      globalcors:
       corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedMethods: "*"
            allowedHeaders: "*"     
            allow-credentials: true      

server:
  port: 8989
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  